spring:
  redis:
    #    默认 0；database是在redis.conf中的databases进行配置，默认是0-15，如果设置为0，则在db[0]中存储数据，参考nms组件的redis配置
    database: 1
    #    默认 localhost
    host: 127.0.0.1
    #    默认 6379
    port: 6379
    #    默认 0；在客户端空闲N秒后关闭连接（0表示禁用）
    timeout: 120
    #    默认 lettuce；如果进行自定义配置，需要添加commons-pool2，LettuceConnectionFactory会自动获取yml中lettuce的配置
    lettuce:
      pool:
        #        默认 8；池在给定时间可以分配的最大连接数。使用负值表示没有限制。
        max-active: 10
        #        默认 8 ：池中“空闲”连接的最大数量。使用负值表示无限数量的空闲连接。
        max-idle: 5
        #        默认 0；目标是要在池中维护的最小空闲连接数。此设置仅在逐次运行之间的时间和正数均为正时才有效。
        min-idle: 2
        #        默认 -1ms；当池耗尽时，在引发异常之前，连接分配应阻塞的最长时间。 使用负值无限期阻止。
        max-wait: 120
  datasource:
    #    JDBC驱动程序的全限定名称。默认情况下根据URL自动检测。
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    数据库的登录用户名。
    username: root
    #    数据库的登录密码。
    password: 123456
    #    数据库的JDBC URL。
    url: jdbc:mysql://127.0.0.1:3306/web_demo?serverTimezone=UTC&allowPublicKeyRetrieval=true