server:
  #  服务端口
  port: 8080
  servlet:
    #    servlet上下文路径，必须以/开头，且不能以/结尾
    context-path: /hik

spring:
  profiles:
    #    当前激活的配置文件是 application-dev.yml，dev环境为spring boot-auto config，pro环境为customize config
    active: dev
  messages:
    #    从resources目录下解析国际化文件，如果有多个，使用“,”进行分隔
    basename: i18n/login,i18n/message
