hik:
  config:
    service:
      name: @name@
      swagger: true
      version: @version@

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: input
      table-prefix: tb_

server:
  port: 7500
  servlet:
    context-path: /@name@

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/web_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    schema: classpath:sql/init.sql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
  profiles:
    active: dev